[versions]
docker = "3.3.0"

[libraries]
docker-java = {module = "com.github.docker-java:docker-java", version.ref = "docker"}
docker-java-client = {module = "com.github.docker-java:docker-java-transport-httpclient5", version.ref = "docker"}
